name: deploy-pages
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: node_modules/.bin/quasar build
      - run: cp -a dist/spa/* docs/
